package com.twitter.graphjet.algorithms.filters;

import com.twitter.graphjet.algorithms.filters.TweetTimeRangeFilter;
import org.junit.Assert;
import org.junit.Test;

public class TweetTimeRangeFilterTest {

  @Test
  public void originalTimeStampFromTweetIdInputPositiveOutputPositive2() {

    // Arrange
    final long id = 70_611_457_338_769_408L;

    // Act
    final long retval = TweetTimeRangeFilter.originalTimeStampFromTweetId(id);

    // Assert result
    Assert.assertEquals(1_305_670_057_984L, retval);
  }

  /*
   * Test generated by Diffblue Deeptest.
   * This test case covers the entire method.
   */

  @Test
  public void timeStampFromTweetIdInputNegativeOutputZero() {

    // Arrange
    final long id = -5_405_765_689_543_753_728L;

    // Act
    final long retval = TweetTimeRangeFilter.timeStampFromTweetId(id);

    // Assert result
    Assert.assertEquals(0L, retval);
  }
  
}
